### ISSUE TITLE
Why use libfuse when you can use a normal folder?

### ISSUE THREAD

**Issue by Spike1377** [devdetour/TelegramFUSE#1]
I saw the video about this project and it seems like libfuse is making it confusing to develop and only works on linux, i dont mind i use linux you should use linux, come to thr linux side of life its better more freedom morr flexibility.

Anyyyway just use a normal folder instad of libfuse, thats what syncthing dose, you give it a folder to keep synced with your computers and it just works. No fake drive mount needed. It just looks a the folder to see if it changed, dosnt need librefuse nice and simpile.

**Comment by dhruvburman97** [comment]
From the docs - incoming requests from the kernel are passed to the main program using callbacks.

so I'm guessing it's because he wants the action of changing the folders to trigger the call rather than constantly running something like os.listdir to check for changes? 

But I like the simplicity of the proposed 'normal folder', gonna research a bit into how this could be done without sacrificing efficiency

**Comment by devdetour** [comment]
Hi, I'm not too familiar with syncthing, but my understanding is this is intended to copy your files from a folder to another location - that's similar to what this project does but not quite the same. Thanks for your suggestion, I'll look at doing something with syncthing in the future!

**Comment by Spike1377** [comment]
It dosen't need to be like syncthing, I just seid that as an example. Im saying having a sync folder on your desktop or home directory might make it easier for people to use.
